# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: env

on:
  push:
    branches: [ "main" ]

jobs:
  world:
    runs-on: windows-11-arm

    steps:
    - name: set
      shell: cmd
      env:
        A: ${{ github.workspace }}
        B: ${{ runner.temp }}
      run: set
